CXX = g++

Base.o: Base.cpp Base.hpp
    $(CXX) -c Base.cpp

Derived.o: Derived.cpp Derived.hpp
    $(CXX) -c Derived.cpp

main: Base.o Derived.o
    $(CXX) Base.o Derived.o -o main

clean:
    rm -f main
    rm -f *.o
